#!/bin/sh

mkdir $configpath

cat /etc/redhat-release
if [ $? == "0" ];then
    distro="CentOS"
    cat /etc/redhat-release|grep 6
    if [ $? == "0" ];then
        version="6"
        ifconfig -a|grep -i "${bondip0mac0}"|grep Link|sed -n "1P"|awk {'print $1'} > ${configpath}nic0
        ifconfig -a|grep -i "${bondip0mac1}"|grep Link|sed -n "1P"|awk {'print $1'} > ${configpath}nic1
    else
        version="Other"
        ifconfig -a|grep -iB 5 "${bondip0mac0}"|grep flags|cut -d ':' -f 1 > ${configpath}nic0
        ifconfig -a|grep -iB 5 ${bondip0mac1}|grep flags|cut -d ":" -f 1 > ${configpath}nic1
    fi
fi

cat /etc/lsb-release|grep Ubuntu
if [ $? == "0" ];then
    distro="Ubuntu"
    cat /etc/lsb-release|grep Ubuntu|grep 14
    if [ $? == "0" ];then
        version="14"
        ifconfig -a|grep -i "${bondip0mac0}"|grep Link|sed -n "1P"|awk {'print $1'} > ${configpath}nic0
        ifconfig -a|grep -i "${bondip0mac1}"|grep Link|sed -n "1P"|awk {'print $1'} > ${configpath}nic1
    else
        version="other"
        echo "todo for ubuntu 12"
        ifconfig -a|grep -i "${bondip0mac0}"|grep Link|sed -n "1P"|awk {'print $1'} > ${configpath}nic0
        ifconfig -a|grep -i "${bondip0mac1}"|grep Link|sed -n "1P"|awk {'print $1'} > ${configpath}nic1
    fi
fi

nic0=`cat ${configpath}nic0`
nic1=`cat ${configpath}nic1`

file1="${configpath}nic0"
file2="${configpath}nic1"

if [ ! -s $file1 ];then
    echo "mac address1 is wrong"
    exit -1
fi

if [ ! -s $file2 ];then
    echo "mac address2 is wrong"
    exit -1
fi

echo $nic0
echo $nic1

systemctl disable NetworkManager
systemctl stop NetworkManager
modprobe --first-time bonding
modinfo bonding

##config nics and start nics
if [ $distro == "CentOS" ];then
    config_centos_nic
    start_centos_nic
elif [ $distro == "Ubuntu" ];then
    config_ubuntu_nic
    start_ubuntu_nic
fi

set +x
