#!/bin/sh


echo "CentOS functions are loaded"

disable_network_manager()
{
yum remove NetworkManager

if [ $? -ne "0" ]; then
	echo "yum not available"
	exit -1
else
	echo "network manager not installed or disabled"
fi
}
config_nic()
{
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-bond${bond0}
DEVICE=bond${bond0}
NAME=bond${bond0}
TYPE=Bond
BONDING_MASTER=yes
ONBOOT=yes
BOOTPROTO=dhcp
BONDING_OPTS="miimon=100 mode=$bondip0mode"
EOF

cat << EOF > /etc/sysconfig/network-scripts/ifcfg-${nic0}
DEVICE=${nic0}
NAME=bond${bond0}-slave
TYPE=Ethernet
BOOTPROTO=none
ONBOOT=yes
MASTER=bond${bond0}
SLAVE=yes
EOF

cat << EOF > /etc/sysconfig/network-scripts/ifcfg-${nic1}
DEVICE=${nic1}
NAME=bond${bond0}-slave
TYPE=Ethernet
BOOTPROTO=none
ONBOOT=yes
MASTER=bond${bond0}
SLAVE=yes
EOF
#config businese network end

#config storage network start
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-bond${bond0}.${bondip1vlanid}
DEVICE=bond${bond0}.${bondip1vlanid}
NAME=bond${bond0}.${bondip1vlanid}
ONBOOT=yes
BOOTPROTO=none
IPADDR=${bondip1}
NETMASK=${bondip1netmask}
#GATEWAY=${bondip1gateway}
VLAN=yes
EOF
#config storage network end
}

start_nic()
{
#ifdown ${nic0}
ifup ${nic0}
#ifdown ${nic1}
ifup ${nic1}
#ifdown bond${bond0}
ifup bond${bond0}
#ifdown bond${bond0}.${bondip1vlanid}
ifup bond${bond0}.${bondip1vlanid}
#service network restart
}
