#!/bin/sh

echo "common function are loaded"

distro_check()
{
    cat /etc/redhat-release &> /dev/null
    if [ $? == "0" ];then
        distro="CentOS"
        version=$(cat /etc/redhat-release|awk '{print $4}'|cut -d '.' -f1)
    fi

    cat /etc/lsb-release|grep Ubuntu &> /dev/null
    if [ $? == "0" ];then
        distro="Ubuntu"
        version=$(cat /etc/lsb-release|grep RELEASE|cut -d '=' -f2|cut -d '.' -f1)
    fi

    echo "current linux is $distro $version"
}

