#!/bin/sh


echo "CentOS functions are loaded"

disable_network_manager()
{
yum remove NetworkManager

if [ $? -ne "0" ]; then
	echo "yum not available"
	exit -1
else
	echo "network manager not installed or disabled"
fi
}


bond_initial()
{
echo "bond initialized"
}

config_nic()
{
if [ $SCRIPT_VERSION == "2017-05-01-cmcc-public-cloud" ]; then

##config manage network
touch /etc/sysconfig/network-scripts/ifcfg-${nic_0}
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-${nic_0}
DEVICE=${nic_0}
NAME=bond0-slave-${nic_0}
TYPE=Ethernet
BOOTPROTO=none
ONBOOT=yes
MASTER=bond0
SLAVE=yes
EOF

touch /etc/sysconfig/network-scripts/ifcfg-${nic_1}
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-${nic_1}
DEVICE=${nic_1}
NAME=bond0-slave-${nic_1}
TYPE=Ethernet
BOOTPROTO=none
ONBOOT=yes
MASTER=bond0
SLAVE=yes
EOF

touch /etc/sysconfig/network-scripts/ifcfg-bond0
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-bond0
DEVICE=bond0
NAME=bond0
TYPE=Bond
BONDING_MASTER=yes
IPADDR=${manage_ip}
GATEWAY=${manage_gateway}
NETMASK=${manage_netmask}
ONBOOT=yes
BOOTPROTO=none
BONDING_OPTS="mode=1 miimon=100"
EOF

##config storage network
touch /etc/sysconfig/network-scripts/ifcfg-${nic_2}
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-${nic_2}
DEVICE=${nic_2}
NAME=bond0-slave-${nic_2}
TYPE=Ethernet
BOOTPROTO=none
ONBOOT=yes
MASTER=bond1
SLAVE=yes
EOF

touch /etc/sysconfig/network-scripts/ifcfg-${nic_3}
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-${nic_3}
DEVICE=${nic_3}
NAME=bond0-slave-${nic_3}
TYPE=Ethernet
BOOTPROTO=none
ONBOOT=yes
MASTER=bond1
SLAVE=yes
EOF

touch /etc/sysconfig/network-scripts/ifcfg-bond1
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-bond1
DEVICE=bond1
NAME=bond1
TYPE=Bond
BONDING_MASTER=yes
IPADDR=${storage_ip}
GATEWAY=${storage_gateway}
NETMASK=${storage_netmask}
ONBOOT=yes
BOOTPROTO=none
BONDING_OPTS="mode=4 miimon=100"
EOF

##config business network
touch /etc/sysconfig/network-scripts/ifcfg-${nic_4}
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-${nic_4}
DEVICE=${nic_4}
NAME=bond0-slave-${nic_4}
TYPE=Ethernet
BOOTPROTO=none
ONBOOT=yes
MASTER=bond2
SLAVE=yes
EOF

touch /etc/sysconfig/network-scripts/ifcfg-${nic_5}
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-${nic_5}
DEVICE=${nic_5}
NAME=bond0-slave-${nic_5}
TYPE=Ethernet
BOOTPROTO=none
ONBOOT=yes
MASTER=bond2
SLAVE=yes
EOF

touch /etc/sysconfig/network-scripts/ifcfg-bond2
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-bond2
DEVICE=bond2
NAME=bond2
TYPE=Bond
BONDING_MASTER=yes
ONBOOT=yes
BOOTPROTO=dhcp
BONDING_OPTS="mode=4 miimon=100"
EOF

elif [ $SCRIPT_VERSION == "2017-07-01-cmcc-private-cloud" ]; then

##config manage network
touch /etc/sysconfig/network-scripts/ifcfg-${nic_0}
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-${nic_0}
DEVICE=${nic_0}
NAME=bond0-slave-${nic_0}
TYPE=Ethernet
BOOTPROTO=none
ONBOOT=yes
MASTER=bond0
SLAVE=yes
EOF

touch /etc/sysconfig/network-scripts/ifcfg-${nic_1}
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-${nic_1}
DEVICE=${nic_1}
NAME=bond0-slave-${nic_1}
TYPE=Ethernet
BOOTPROTO=none
ONBOOT=yes
MASTER=bond0
SLAVE=yes
EOF

touch /etc/sysconfig/network-scripts/ifcfg-bond0
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-bond0
DEVICE=bond0
NAME=bond0
TYPE=Bond
BONDING_MASTER=yes
IPADDR=${manage_ip}
GATEWAY=${manage_gateway}
NETMASK=${manage_netmask}
ONBOOT=yes
BOOTPROTO=none
BONDING_OPTS="mode=1 miimon=100"
EOF

##config business network
touch /etc/sysconfig/network-scripts/ifcfg-${nic_2}
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-${nic_2}
DEVICE=${nic_2}
NAME=bond0-slave-${nic_2}
TYPE=Ethernet
BOOTPROTO=none
ONBOOT=yes
MASTER=bond1
SLAVE=yes
EOF

touch /etc/sysconfig/network-scripts/ifcfg-${nic_3}
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-${nic_3}
DEVICE=${nic_3}
NAME=bond0-slave-${nic_3}
TYPE=Ethernet
BOOTPROTO=none
ONBOOT=yes
MASTER=bond1
SLAVE=yes
EOF

touch /etc/sysconfig/network-scripts/ifcfg-bond1
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-bond1
DEVICE=bond1
NAME=bond1
TYPE=Bond
BONDING_MASTER=yes
ONBOOT=yes
BOOTPROTO=dhcp
BONDING_OPTS="mode=4 miimon=100"
EOF

##config storage network
touch /etc/sysconfig/network-scripts/ifcfg-bond1.${storage_vlanid}
cat << EOF > /etc/sysconfig/network-scripts/ifcfg-bond1.${storage_vlanid}
DEVICE=bond1.${storage_vlanid}
NAME=bond1.${storage_vlanid}
BOOTPROTO=none
ONPARENT=yes
IPADDR=${storage_ip}
GATEWAY=${storage_gateway}
NETMASK=${storage_netmask}
VLAN=yes
ONBOOT=yes
EOF

else

echo "unsupport SCRIPT_VERSION"; exit -1

fi
}

start_nic()
{
service network restart
}
